### PR TITLE
Create harbour-smpc-es.ts

### PR DESCRIPTION
**Pull request by ghost**
Hi djselbeck
Any news of this ??
I have plan to translate this great to spanish if you have plan to stabilize this pretty app.

### CODE REVIEW

**Comment by djselbeck** [comment]
If you provide it I will merge it and probably release it. I will however not add new features to SMPC because Jolla never released the source code of silica qml components which is too disappointing.

**Comment by Caballlero** [comment]
I understand you, i have hearded rumors than jolla have plan to opensource silica, but i do not when will do. I stay any way with SFOS it is the only operating system I like.  Android is horribly

**Comment by Caballlero** [comment]
Thank you for the release! :  )

**Comment by ghost** [comment]
Hi djselbeck
What is the main harbour-smpc.ts ? to clone  my *-es.ts
Thanks

**Pull request closed without merging**
